### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by lawrence615** [CoreProc/laravel-db-backup#3]
Hi,

Getting this error when I run php artisan db:backup;

`is_dir() expects parameter 1 to be a valid path, array given`

Is there something am missing?

Thanks

**Comment by chrisbjr** [comment]
Hi @lawrence615 were you able to resolve this issue?

**Comment by shkabo** [comment]
Getting the same issue

Update:
In `coreproc\laravel-db-backup\src\LaravelDbBackupServiceProvider.php` change `$this->package('coreproc/laravel-db-backup');` to `$this->package('coreproc/laravel-db-backup', null, __DIR__);` and it will work tho now I got a problem with exported file name. Instead of `{db name}_{timestamp}.sql` I got only `_{timestamp}.sql`
Anyway, the problem was with config file that was not being loaded. L4 by default tried to locate config folder in it's assumed location but w/o luck. With `__DIR__` we said to it 'Look, this is the root folder, search now', so he did and managed to locate it :)
All was done/tested on vBox Homestead machine w/ L4.2 installation

**Comment by chrisbjr** [comment]
Thanks for the update @shkabo - will see if we can recreate this issue and update it according to your instructions.

**Comment by snipe** [comment]
I am also having this issue with the latest version. Reverting to 0.2.2 resolves the issue, but only leaves the _{timestamp}.sql as the filename.

**Comment by snipe** [comment]
I think I see what's happening here.

In `BaseCommand.php`, it sets the method `getDumpsPath()`.

```
protected function getDumpsPath()
{
    return Config::get('laravel-db-backup::path');
}
```

In `BackupCommand.php`, if you dump that `$this->getDumpsPath()` out:

```
protected function checkDumpFolder()
{
    $dumpsPath = $this->getDumpsPath();
    print_r($dumpsPath);
    if ( ! is_dir($dumpsPath)) {
        mkdir($dumpsPath);
    }
}
```

You get an empty array:

```
snipe-it agianotto$ php artisan db:backup
Array
(
)

  [ErrorException]
  is_dir() expects parameter 1 to be a valid path, array given
```

Is it possibly not reading your config file?

**Comment by snipe** [comment]
`print_r(Config::get('laravel-db-backup::path'));`

also results in an empty array.

**Comment by chrisbjr** [comment]
Thanks for looking into this @snipe. I have an idea on how to fix it now.

**Comment by snipe** [comment]
No problem. Let me know if I can help in any way.

**Comment by edbentinck** [comment]
+1. Any chance of this being resolved soon?

**Comment by chrisbjr** [comment]
Hi @edbentinck, I believe this has been fixed with the previous pull request. You can pull v0.3.1 to get the latest change.
